### PR TITLE
Updated to comply with PEP8

### PR DESCRIPTION
**Pull request by growland2**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
Reviewing all code since this is the first PR.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-:-NitWyI9ASsbPdJe1Sge:b-17y1k6)* status: all files reviewed, 3 unresolved discussions (waiting on @growland2)

___
*[`single_var_vcf_maker.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitUbdF2HRFezhZPf-s:-NitUbdF2HRFezhZPf-t:b-ge2ifw) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L38)):*
> ```Python
> ##contig=<ID=X,length=155270560,assembly=b37>
> ##contig=<ID=Y,length=59373566,assembly=b37>
> #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT"""
> ```

We'll want to run this for 38 too at some point. Could you make this header specific to 37, and enable different reference genomes to be used (i.e. 37/38). 

The reference info for each variant is in the input file, so perhaps you could use that in your logic to select the correct header info. No need to implement a 38 header for now, just to structure the code to allow it later. Anything other than GRCh37 for reference should raise an error for now.



_Code quote:_
```Python
VCF_HEADER = """##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=V1_evidence,Number=.,Type=String,Description="Free text from scientists">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT"""
```
___
*[`single_var_vcf_maker.py` line 83 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitWNuL0LJYs-8YVkZR:-NitWNuL0LJYs-8YVkZS:b-xrpsjb) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L83)):*
> ```Python
>     if len(ref) > 1 and len(alt) > 1:
>         print(f"REF/ALT are not valid for row index: {index}")
>         continue
> ```

Maybe this should be a get_variant(row) function



_Code quote:_
```Python
    variant = row["V1"].strip()
    result = re.search(PATTERN, variant)
    try:
        chrom = result[1]
    except TypeError:
        print(f"CHROM could not be found for row index: {index}")
        continue
    try:
        pos = result[2]
    except TypeError:
        print(f"POS could not be found for row index: {index}")
        continue

    try:
        ref = result[3]
    except TypeError:
        print(f"REF could not be found for row index: {index}")
        continue

    try:
        alt = result[4]
    except TypeError:
        print(f"ALT could not be found for row index: {index}")
        continue

    if len(ref) > 1 and len(alt) > 1:
        print(f"REF/ALT are not valid for row index: {index}")
        continue
```
___
*[`single_var_vcf_maker.py` line 92 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitWTaC41tDkJo3DfK7:-NitWTaC41tDkJo3DfK8:b-5ppd9e) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L92)):*
> ```Python
>     else:
>         print(f"Zygosity is not valid for row index: {index}")
>         continue
> ```

and get_zygosity(row)



_Code quote:_
```Python
    zygos = row["V1_zygosity"].strip()
    if zygos in ["het", "Het", "heterozygous", "Heterozygous"]:
        GT = "0/1"
    elif zygos in ["hom", "Hom", "homozygous", "Homozygous"]:
        GT = "1/1"
    else:
        print(f"Zygosity is not valid for row index: {index}")
        continue
```

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

___
*[`single_var_vcf_maker.py` line 38 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitUbdF2HRFezhZPf-s:-Nj7OFWW71XOySrFooSc:b-2i1f5n) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L38)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

We'll want to run this for 38 too at some point. Could you make this header specific to 37, and enable different reference genomes to be used (i.e. 37/38). 

The reference info for each variant is in the input file, so perhaps you could use that in your logic to select the correct header info. No need to implement a 38 header for now, just to structure the code to allow it later. Anything other than GRCh37 for reference should raise an error for now.
</blockquote></details>

Added B38 header and put into a dict along with B37.
___
*[`single_var_vcf_maker.py` line 83 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitWNuL0LJYs-8YVkZR:-Nj7P7Of5XjgHtdUeQGw:b-896fix) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L83)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Maybe this should be a get_variant(row) function
</blockquote></details>

Done.
___
*[`single_var_vcf_maker.py` line 92 at r1](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-NitWTaC41tDkJo3DfK7:-Nj7PJqQ2rS3SymQhLCA:b-896fix) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/a7f90a7775d19ce0933baf8ff0c795d6b36f4ea9/single_var_vcf_maker.py#L92)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

and get_zygosity(row)
</blockquote></details>

Done.
___
*[`single_var_vcf_maker.py` line 77 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7OdET-JY57THJ2uBu:-Nj7OdET-JY57THJ2uBv:b-ez6jgp) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L77)):*
> ```Python
> 
> # Regex pattern for extracting chrom,pos,ref,alt
> PATTERN = r"([1-9]?|1[0-9]?|2[0-2]?|X|Y):(\d+):([ACGT]+):([ACGT]+)"
> ```

Fixed regex pattern as old regex would miss chrom 3-9
___
*[`single_var_vcf_maker.py` line 108 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7PS3Z1wt6CmEEZmMt:-Nj7PS3Z1wt6CmEEZmMu:bkc41uq) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L108)):*
> ```Python
>     g_build = row["Genome_build"].strip()
>     # At the moment only accepting b37
>     if g_build in ["GRCh37"]:
> ```

This line will need to be changed to allow GRCh38

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1)* status: all files reviewed, 5 unresolved discussions (waiting on @growland2)

___
*[`single_var_vcf_maker.py` line 101 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7XGdwEONzYti8vmUH:-Nj7XGdwEONzYti8vmUI:b-iyvhz2) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L101)):*
> ```Python
>         return "1/1"
>     raise ValueError(f"Zygosity is not valid for row index: {r_index}")
>     
> ```

whitespace
___
*[`single_var_vcf_maker.py` line 105 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7XJMs3uf3rFxugoyn:-Nj7XJMs3uf3rFxugoyo:b32x0h) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L105)):*
> ```Python
> # Loop and parse out variants in the excel and export in VCF format
> for index, row in df.iterrows():
>     
> ```

ws

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`single_var_vcf_maker.py` line 101 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7XGdwEONzYti8vmUH:-Nj7ZbE8858DNtnCRsZ8:b-896fix) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L101)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[`single_var_vcf_maker.py` line 105 at r3](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1#-Nj7XJMs3uf3rFxugoyn:-Nj7Z_eW77qcTlzABzRn:b-896fix) ([raw file](https://github.com/eastgenomics/single_variant_vcf/blob/36626bf3f33e9b1add801bb266dc62ec1e63bfa9/single_var_vcf_maker.py#L105)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/single_variant_vcf/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
